# rule identifiers to exclude from running
disabled_rules:
  - variable_name
  - trailing_whitespace
  - todo
  - conditional_binding_cascade
  - mark
  - vertical_whitespace
  - syntactic_sugar
  - unused_closure_parameter
  - closure_parameter_position
  - redundant_string_enum_value
  - large_tuple
  - shorthand_operator
  - vertical_parameter_alignment
  - line_length
# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
included:
  - weapp-ios

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - weapp-ios/Constants/*

line_length:
  warning: 200
  error: 1000

file_length:
  warning: 700
  error: 1000

type_body_length:
  warning: 700
  error: 1000

function_parameter_count:
  warning: 7
  error: 10

cyclomatic_complexity:
  warning: 15
  error: 20

function_body_length:
  warning: 100
  error: 150

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 150
    error: 1000
